// @/config/auth-guard.config.ts
import { APP_ROUTES } from './routes';

export const ADMIN_ONLY_ROUTES = [
    APP_ROUTES.MANAGE.USERS,
    APP_ROUTES.MANAGE.CATEGORIES,
    APP_ROUTES.MANAGE.TRANSACTIONS,
    APP_ROUTES.MANAGE.VIPS,
    APP_ROUTES.MANAGE.STATISTICS.USERS,
    APP_ROUTES.MANAGE.STATISTICS.TRANSACTIONS,
];